### ISSUE TITLE
Add background with CSS animations

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/links#3]
**Is your feature request related to a problem? Please describe.**
The background now applied looks so dull, change it and add CSS or JS animations to make it look better.

**Describe the solution you'd like**
just be creative as you like.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by ramdhanihendrie** [comment]
I am interested in this issue, please assign it to me. I want to add gradient color-changing animation like [this](https://www.gradient-animator.com/)

**Comment by akashrchandran** [comment]
@ramdhanihendrie  Assigned.
